apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sockshop-gateway
  namespace: sock-shop
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: sockshop-http
      protocol: HTTP
    hosts:
    - "sockshop.mvdp.eu"
